### ISSUE TITLE
Error - Your custom storage adapter must use strict mode.

### ISSUE THREAD

**Issue by geelakey** [mmornati/ghost-cloudinary-store#13]
I've just recently started getting this error and not sure how to resolve. It didn't appear to be happening previously - is it possible Ghost was updated to enforce strict mode?

`Unhandled rejection IncorrectUsageError: Your custom storage adapter must use strict mode.
   2018-03-16T15:40:06.10+1100 [APP/PROC/WEB/0] ERR     at new IncorrectUsageError (/home/vcap/app/node_modules/ghost/node_modules/ghost-ignition/lib/errors/index.js:79:23)
   2018-03-16T15:40:06.10+1100 [APP/PROC/WEB/0] ERR     at Object.getStorage (/home/vcap/app/node_modules/ghost/core/server/adapters/storage/index.js:35:19)
   2018-03-16T15:40:06.10+1100 [APP/PROC/WEB/0] ERR     at setupSiteApp (/home/vcap/app/node_modules/ghost/core/server/web/site/app.js:74:73)
   2018-03-16T15:40:06.10+1100 [APP/PROC/WEB/0] ERR     at setupParentApp (/home/vcap/app/node_modules/ghost/core/server/web/parent-app.js:54:36)
   2018-03-16T15:40:06.10+1100 [APP/PROC/WEB/0] ERR     at /home/vcap/app/node_modules/ghost/core/server/index.js:81:48
   2018-03-16T15:40:06.10+1100 [APP/PROC/WEB/0] ERR     at tryCatcher (/home/vcap/app/node_modules/bluebird/js/release/util.js:16:23)
   2018-03-16T15:40:06.10+1100 [APP/PROC/WEB/0] ERR     at Promise._settlePromiseFromHandler (/home/vcap/app/node_modules/bluebird/js/release/promise.js:512:31)
   2018-03-16T15:40:06.10+1100 [APP/PROC/WEB/0] ERR     at Promise._settlePromise (/home/vcap/app/node_modules/bluebird/js/release/promise.js:569:18)
   2018-03-16T15:40:06.10+1100 [APP/PROC/WEB/0] ERR     at Promise._settlePromise0 (/home/vcap/app/node_modules/bluebird/js/release/promise.js:614:10)
   2018-03-16T15:40:06.10+1100 [APP/PROC/WEB/0] ERR     at Promise._settlePromises (/home/vcap/app/node_modules/bluebird/js/release/promise.js:693:18)
   2018-03-16T15:40:06.10+1100 [APP/PROC/WEB/0] ERR     at Promise._fulfill (/home/vcap/app/node_modules/bluebird/js/release/promise.js:638:18)
   2018-03-16T15:40:06.10+1100 [APP/PROC/WEB/0] ERR     at PromiseArray._resolve (/home/vcap/app/node_modules/bluebird/js/release/promise_array.js:126:19)
   2018-03-16T15:40:06.10+1100 [APP/PROC/WEB/0] ERR     at PromiseArray._promiseFulfilled (/home/vcap/app/node_modules/bluebird/js/release/promise_array.js:144:14)
   2018-03-16T15:40:06.10+1100 [APP/PROC/WEB/0] ERR     at Promise._settlePromise (/home/vcap/app/node_modules/bluebird/js/release/promise.js:574:26)
   2018-03-16T15:40:06.10+1100 [APP/PROC/WEB/0] ERR     at Promise._settlePromise0 (/home/vcap/app/node_modules/bluebird/js/release/promise.js:614:10)
   2018-03-16T15:40:06.10+1100 [APP/PROC/WEB/0] ERR     at Promise._settlePromises (/home/vcap/app/node_modules/bluebird/js/release/promise.js:693:18)
   2018-03-16T15:40:06.10+1100 [APP/PROC/WEB/0] ERR SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

**Comment by mmornati** [comment]
Ah yeah. Maybe you are right, there is anything changed in the ghost platform.
I will test it out this evening.

**Comment by mmornati** [comment]
Fixed thanks to the excellent @eexit work. You can install the 3.0.1 of the plugin to have all working back again.
